linux_amd64_task:
  container:
    image: alpine:latest
  test_script:
    - apk add alpine-sdk linux-headers bison libretls-dev libevent-dev
    - ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - make regress

linux_arm_task:
  arm_container:
    image: alpine:latest
  test_script:
    - apk add alpine-sdk linux-headers bison libretls-dev libevent-dev
    - ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - make regress

freebsd_13_task:
  freebsd_instance:
    image_family: freebsd-13-0
  test_script:
    - pkg install -y libevent libressl pkgconf
    - ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - make regress

mac_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  test_script:
    - brew install libevent libretls
    - ./configure CFLAGS='-O2 -pipe -Wno-deprecated-declarations' -Werror
    - make
    - SKIP_RUNTIME_TESTS=1 make regress
