linux_amd64_task:
  container:
    image: alpine:latest
  test_script:
    - apk add alpine-sdk linux-headers bison libretls-dev libevent-dev
    - ./configure
    - make
    - make regress

linux_arm_task:
  arm_container:
    image: alpine:latest
  test_script:
    - apk add alpine-sdk linux-headers bison libretls-dev libevent-dev
    - ./configure
    - make
    - make regress

freebsd_13_task:
  freebsd_instance:
    image_family: freebsd-13-0
  test_script:
    - pkg install -y libevent libressl pkgconf
    - ./configure
    - make
    - make regress

mac_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  test_script:
    - brew install libevent libretls
    - LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib -lcrypto -lssl $(pkg-config --libs libevent libtls)" ./configure CFLAGS="-I/opt/homebrew/opt/openssl@1.1/include $(pkg-config --cflags libevent libtls)" || (echo ; cat config.log ; false)
    - make
    - SKIP_RUNTIME_TESTS=1 make regress
